version: '3.10'

services:
  symbol-list-collector:
    build:
      context: .
      dockerfile: Dockerfile.symbol_list_collection
    container_name: symbol_list_collector
    volumes:
      - ./logs:/app/var/logs
    restart: on-failure
    command: /app/start_with_env.sh
    